#
# Copyright (c) LSE
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY LSE AS IS AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL LSE BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

TARGET	  = skate
OBJS	  = \
	    gfx.o \
	    park.o \
	    skate.o \
	    skater.o \

ROM_TITLE = "skate"
ROM_FILES = \
	    res/box.bmp \
	    res/boxup.bmp \
	    res/crash.bmp \
	    res/flip1.bmp \
	    res/flip2.bmp \
	    res/flip3.bmp \
	    res/flip4.bmp \
	    res/flip5.bmp \
	    res/logo.bmp \
	    res/rail.bmp \
	    res/rotate1.bmp \
	    res/rotate2.bmp \
	    res/rotate3.bmp \
	    res/rotate4.bmp \
	    res/rotate5.bmp \
	    res/skater1.bmp \
	    res/skater2.bmp \
	    res/skater3.bmp \
	    res/skater4.bmp \
	    res/skater5.bmp \
	    res/skater6.bmp \
	    res/skaterup.bmp \
	    res/slide1.bmp \
	    res/slide2.bmp \

include ../roms.mk
